openapi: 3.0.0
info:
  title: Fake NHL API
  description: Simulated NHL hockey game results API
  version: 1.0.0
paths:
  /api/game-results/{date}:
    get:
      summary: Get game results for a specific date
      parameters:
        - name: date
          in: path
          required: true
          description: The date for which game results are requested (YYYY-MM-DD)
          schema:
            type: string
            format: date
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    homeTeam:
                      type: string
                      description: The name of the home team
                    awayTeam:
                      type: string
                      description: The name of the away team
                    homeTeamScore:
                      type: array
                      description: Scores for the home team in each period
                      items:
                        type: integer
                    awayTeamScore:
                      type: array
                      description: Scores for the away team in each period
                      items:
                        type: integer
                    finalHomeScore:
                      type: integer
                      description: The final score for the home team
                    finalAwayScore:
                      type: integer
                      description: The final score for the away team
                    periods:
                      type: integer
                      description: The number of periods in the game
                    date:
                      type: string
                      format: date-time
                      description: The date and time of the game
        '500':
          description: Internal Server Error
