openapi: 3.0.0
info:
  title: Fake NHL API
  description: Simulated NHL hockey game results API
  version: 1.0.0
servers:
  - url: http://localhost:3000
    description: Development Server

paths:
  /api/game-results/{date}:
    get:
      summary: Get game results for a specific date
      parameters:
        - name: date
          in: path
          required: true
          description: The date for which game results are requested (YYYY-MM-DD)
          schema:
            type: string
            format: date
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    homeTeam:
                      type: string
                    awayTeam:
                      type: string
                    homeScore:
                      type: integer
                    awayScore:
                      type: integer
                    periods:
                      type: integer
                    date:
                      type: string
                      format: date-time
        '500':
          description: Internal Server Error

  /api/team-results/{teamName}:
    get:
      summary: Get the last 5 game results for a specific team (after 3 periods)
      parameters:
        - name: teamName
          in: path
          required: true
          description: The name of the team for which game results are requested
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    homeTeam:
                      type: string
                    awayTeam:
                      type: string
                    resultAfterThirdPeriod:
                      type: string
                    date:
                      type: string
                      format: date-time
        '500':
          description: Internal Server Error
